[package]
name = "verify-smt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2b-rs = "0.2"
blake2-rfc = "0.2.18"

[dev-dependencies]
hex-literal = "0.2.2"
hex = "0.4.3"
